src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    private $created_date;

    #[ORM\Column(type: 'text', nullable: true)]
    private $message;

    #[ORM\ManyToOne(targetEntity: Posts::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private $post;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private $posted_by;

    public function __toString()
    {
        return $this->message;
    }

    public function __construct()
    {
        $this->created_date = new \DateTime();
        $this->created_date->format("Y-m-d H:i:s");
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getPost(): ?Posts
    {
        return $this->post;
    }

    public function setPost(?Posts $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getPostedBy(): ?User
    {
        return $this->posted_by;
    }

    public function setPostedBy(?User $posted_by): self
    {
        $this->posted_by = $posted_by;

        return $this;
    }
}

src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $created_date;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\ManyToOne(targetEntity: Board::class, inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private $fk_board;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comments::class, orphanRemoval: true)]
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->created_date = new DateTime();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getFkBoard(): ?Board
    {
        return $this->fk_board;
    }

    public function setFkBoard(?Board $fk_board): self
    {
        $this->fk_board = $fk_board;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostsType.php
<?php

namespace App\Form;

use App\Entity\Posts;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class PostsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('created_date',DateType::class,[
                'label' => 'Created date (Keep empty for local date)'
            ])
            ->add('title')
            ->add('description')
            ->add('fk_board')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Posts::class,
        ]);
    }
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Posts;
use App\Form\PostsType;
use App\Entity\Comments;
use App\Entity\User;
use App\Form\CommentsType;
use App\Repository\PostsRepository;
use App\Repository\CommentsRepository;
use ContainerObudBMh\getUserService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


#[Route('/posts')]
class PostsController extends AbstractController
{
    #[Route('/', name: 'app_posts_index', methods: ['GET'])]
    public function index(PostsRepository $postsRepository): Response
    {
        return $this->render('posts/index.html.twig', [
            'posts' => $postsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_posts_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PostsRepository $postsRepository): Response
    {
        $post = new Posts();
        $form = $this->createForm(PostsType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postsRepository->add($post);
            return $this->redirectToRoute('app_posts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('posts/new.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_posts_show', methods: ['GET','POST'])]
    // #[ParamConverter('post', options:['id' => 'id'])]
    public function show(Posts $post,Request $request, CommentsRepository $commentsRepository): Response
    {
        $comment = new Comments();
        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $comment->setPost($post);
            date_default_timezone_set('Europe/Paris');
            $date = new \DateTime();
            $date->format("Y-m-d H:i:s");
            $comment->setCreatedDate( $date );
            $comment->setPostedBy($user);
            $commentsRepository->add($comment);
            header("Refresh:0");
            // return $this->redirectToRoute('app_comments_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('posts/show.html.twig', [
            'post' => $post,
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_posts_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Posts $post, PostsRepository $postsRepository): Response
    {
        $form = $this->createForm(PostsType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postsRepository->add($post);
            return $this->redirectToRoute('app_posts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('posts/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_posts_delete', methods: ['POST'])]
    public function delete(Request $request, Posts $post, PostsRepository $postsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $postsRepository->remove($post);
        }

        return $this->redirectToRoute('app_posts_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/posts/_delete_form.html.twig
<form method="post" action="{{ path('app_posts_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn">Delete</button>
</form>

templates/posts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Posts{% endblock %}

{% block body %}
<div id="body">
    <h1>Edit Posts</h1>
        {% for role in app.user.roles %}
        <div>
            Role: {{role}}
        </div>
    {% endfor %}
    {{ include('posts/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_posts_index') }}">back to list</a>

    {% for role in app.user.roles %}
        {% if role == 'ROLE_INSIDER' %}
            {{ include('posts/_delete_form.html.twig') }}
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posts index{% endblock %}

{% block body %}
<div id="body">
    <h1>Posts index</h1>

    <table class="table" id="table-list">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Created Date</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.createdDate ? post.createdDate|date('Y-m-d') : '' }}</td>
                <td>{{ post.description }}</td>
                <td>
                    <a href="{{ path('app_posts_show', {'id': post.id}) }}">show</a>
                    <a href="{{ path('app_posts_edit', {'id': post.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_posts_new') }}" id="create">Create new</a>
</div>
{% endblock %}

templates/posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Posts{% endblock %}

{% block body %}
<div id="body">
    <h1>Create new Posts</h1>

    {{ include('posts/_form.html.twig') }}

    <a href="{{ path('app_posts_index') }}">back to list</a>
</div>
{% endblock %}

templates/posts/show.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ encore_entry_link_tags('post') }}
{% endblock %}
{% block title %}Posts{% endblock %}

{% block body %}
<div id="body" class="show">
    <h1> Post: {{ post.title }} </h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Created Date</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.createdDate ? post.createdDate|date('Y-m-d') : '' }}</td>
                <td>{{ post.description }}</td>
            </tr>
        </tbody>
    </table>
    
    {% for comment in post.comments %}
        <p>{{ comment }}<small >{{ comment.createdDate|date('j F, Y, g:i a') }}</br>posted by: {{ comment.postedBy }}</small></p>
        </br>
    {% endfor %}
    {{ include('comments/_form.html.twig') }}

    <a href="{{ path('app_posts_index') }}">Back to list</a>
    <a href="{{ path('app_posts_edit', {'id': post.id}) }}">Edit</a>

    {% for role in app.user.roles %}
        {% if role == 'ROLE_INSIDER' %}
            {{ include('posts/_delete_form.html.twig') }}
        {% endif %}
    {% endfor %}
</div>
{% endblock %}